config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :leases
  resources :buildings
  resources :property_managers do
    resources :reviews, only: [:index]
  end
  resources :users


  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  root 'application#home'
  get '/about', to: 'application#about', as: :about
  get '/statistics', to:'application#statistics',as: :statistics

  delete '/reviews/:id', to: 'reviews#destroy', as: :delete_review

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/property_manager.rb
class PropertyManager < ApplicationRecord
  has_many :buildings
  has_many :leases, through: :buildings
  has_many :reviews

  def average(att)
    if self.reviews
      ratings = self.reviews.map {|r| r[att]}
      ratings.inject(:+) / ratings.size
    else
      "No reviews yet"
    end
  end

  def leases
    self.buildings.map{|b| b.leases}.flatten
  end

  def self.get_link(return_text)
    name = return_text.split(" - ").first
    PropertyManager.all.find_by(name:name)
  end


  def self.highest_rated
    value = 0
    highestrated = ''
    self.rated_property_managers.each{|pm| value = pm.overall and highestrated = "#{pm.name} - #{pm.overall}" if pm.overall > value}
    highestrated
  end

  def self.lowest_rated
    value = 10
    lowestrated = ''
    self.rated_property_managers.each{|pm| value = pm.overall and lowestrated = "#{pm.name} - #{pm.overall}" if pm.overall < value}
    lowestrated
  end

  def self.most_leases
    count = 0
    most = ''
    self.rated_property_managers.each{|pm| count = pm.leases.size and most = "#{pm.name} - #{pm.leases.size}" if pm.leases.size > count}
    most
  end

  def average_rent
    rents = self.leases.map{|l| l.rent}
    rents.inject(:+) / rents.size
  end

  def overall
      (self.average("niceness") + self.average("value") + self.average("accessibility") + self.average("response_time")) / 4.0
  end

  def self.highest(att)
    num = 0
    highest = ''
    self.rated_property_managers.each{|pm| num = pm.average(att) and highest = "#{pm.name} - #{pm.average(att)}"  if pm.average(att) > num}
    highest
  end

  def reviews
    leases_with_reviews = self.leases.select do |lease|
      lease.review
    end
    if !leases_with_reviews.empty?
      leases_with_reviews.map {|lease| lease.review}
    end
  end

  def best_review
    max = self.reviews.map do |review|
      review.rating
    end.max
    self.reviews.find do |review|
      review.rating == max
    end
  end

  def has_brooklyn?
    !self.buildings.select{|b| b.borough == "Brooklyn"}.empty?
  end

  def brooklyn_rating
    sum = 0

    num_of_buildings = self.buildings.select{|b| b.borough == "Brooklyn"}.size
    self.buildings.each{|b| sum += b.rating if !b.leases.empty? && b.borough == "Brooklyn"}

    sum / num_of_buildings
  end


  def has_queens?
    !self.buildings.select{|b| b.borough == "Queens"}.empty?
  end

  def queens_rating
    sum = 0

    num_of_buildings = self.buildings.select{|b| b.borough == "Queens"}.size
    self.buildings.each{|b| sum += b.rating if !b.leases.empty? && b.borough == "Queens"}

    sum / num_of_buildings
  end

  def has_si?
    !self.buildings.select{|b| b.borough == "Staten Island"}.empty?
  end

  def si_rating
    sum = 0

    num_of_buildings = self.buildings.select{|b| b.borough == "Staten Island"}.size
    self.buildings.each{|b| sum += b.rating if !b.leases.empty? && b.borough == "Staten Island"}

    sum / num_of_buildings
  end


  def has_manhattan?
    !self.buildings.select{|b| b.borough == "Manhattan"}.empty?
  end

  def manhattan_rating
    sum = 0

    num_of_buildings = self.buildings.select{|b| b.borough == "Manhattan"}.size
    self.buildings.each{|b| sum += b.rating if !b.leases.empty? && b.borough == "Manhattan"}

    sum / num_of_buildings
  end


  def self.highest_per_manhattan
    max = 0
    highest = ''

    self.rated_property_managers.each{|pm|
      if pm.has_manhattan?
       max = pm.manhattan_rating and highest = "#{pm.name} - #{pm.manhattan_rating}" if pm.manhattan_rating > max
      end
    }
    highest
  end

  def self.highest_per_brooklyn
    max = 0
    highest = ''

    self.rated_property_managers.each{|pm|
      if pm.has_brooklyn?
       max = pm.brooklyn_rating and highest = "#{pm.name} - #{pm.brooklyn_rating}" if pm.brooklyn_rating > max
      end
    }
    highest
  end

  def self.highest_per_queens
    max = 0
    highest = ''

    self.rated_property_managers.each{|pm|
      if pm.has_queens?
       max = pm.queens_rating and highest = "#{pm.name} - #{pm.queens_rating}" if pm.queens_rating > max
      end
    }
    highest
  end

  def self.highest_per_si
    max = 0
    highest = ''

    self.rated_property_managers.each{|pm|
      if pm.has_si?
       max = pm.si_rating and highest = "#{pm.name} - #{pm.si_rating}" if pm.si_rating > max
      end
    }
    highest
  end


  def worst_review
    min = self.reviews.map do |review|
      review.rating
    end.min
    self.reviews.find do |review|
      review.rating == min
    end
  end

  def self.rated_property_managers
    PropertyManager.all.select {|pm| pm.reviews}
  end




end

app/controllers/property_managers_controller.rb
class PropertyManagersController < ApplicationController
  before_action :retrieve, only: [:show]

  def index
    @property_managers = PropertyManager.all
  end

  def show
  end

  




  private

  def retrieve
    @property_manager = PropertyManager.find(params[:id])
  end
end

app/helpers/property_managers_helper.rb
module PropertyManagersHelper
end

app/views/property_managers/index.html.erb
<h1>Property Managers</h1>

<div class="wrapper">
  <table class='table table-striped'>
    <thead class="thead-dark">
      <tr>
        <th>Name</th>
        <th>Buildings Owned</th>
      </tr>
    </thead>
    <tbody>
      <% @property_managers.each do |manager| %>
        <tr>
          <td><%= link_to manager.name, property_manager_path(manager) %></td>
          <td><%= manager.buildings.size %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/property_managers/show.html.erb
<h1><%= @property_manager.name %></h1>

<%= link_to "< All property managers", property_managers_path, class:"back-button" %>

<div class="wrapper">
  <div class="left-col">
    <h4>Buildings Owned:</h4>
    <% if @property_manager.reviews %>
      <p>Average Monthly Rent: $<%= @property_manager.average_rent %></p>
    <% end %>
    <ul>
      <% @property_manager.buildings.each do |building| %>
        <li><%= building.address %>, <%= building.borough %></li>
      <% end %>
    </ul>
  </div>

  <div class="right-col">
    <% if @property_manager.reviews %>
    <h4 class="right">Average Ratings</h4>
    <p class="right">Based on <%= @property_manager.reviews.size %> reviews</p>
    <table class="table table-striped">
      <thead class="thead-dark">
        <tr>
          <th>Category</th>
          <th>Avg Rating</th>
        </tr>
      </thead>
      <tr>
        <th scope="row">Niceness</th>
        <td><%= @property_manager.average("niceness") %></td>
      </tr>
      <tr>
        <th scope="row">Value</th>
        <td><%= @property_manager.average("value") %></td>
      </tr>
      <tr>
        <th scope="row">Response Time</th>
        <td><%= @property_manager.average("response_time") %></td>
      </tr>
      <tr>
        <th scope="row">Accessibility</th>
        <td><%= @property_manager.average("accessibility") %></td>
      </tr>
      <tr>
        <th scope="row">Overall</th>
        <td><%= @property_manager.overall %></td>
      </tr>
    </table>
  </div>
</div>


<div class="wrapper wrapper-two">
  <h1 class="">Reviews</h1>
  <table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th>Rating</th>
        <th>Review</th>
        <th>Building</th>
        <th>User Name</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td class="bold" colspan="4">Best Review</td>
      </tr>
      <tr>
        <td><%= @property_manager.best_review.rating %></td>
        <td><%= @property_manager.best_review.content %></td>
        <td><%= @property_manager.best_review.lease.building.address %></td>
        <td><%= @property_manager.best_review.lease.user.name %></td>
      </tr>
      <tr>
        <td class="bold" colspan="4">Worst Review</td>
      </tr>
      <tr>
        <td><%= @property_manager.worst_review.rating %></td>
        <td><%= @property_manager.worst_review.content %></td>
        <td><%= @property_manager.worst_review.lease.building.address %></td>
        <td><%= @property_manager.worst_review.lease.user.name %></td>
      </tr>
    </tbody>

  </table>
</div>


<div class="wrapper wrapper-two wrapper-last">
  <%= link_to "See All Reviews", property_manager_reviews_path(@property_manager), class:"btn btn-info extra-space" %>
</div>

<% else %>
  <p>No reviews yet!</p>
<% end %>