config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :leases
  resources :buildings
  resources :property_managers do
    resources :reviews, only: [:index]
  end
  resources :users


  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  root 'application#home'
  get '/about', to: 'application#about', as: :about
  get '/statistics', to:'application#statistics',as: :statistics

  delete '/reviews/:id', to: 'reviews#destroy', as: :delete_review

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/building.rb
class Building < ApplicationRecord
  belongs_to :property_manager
  has_many :leases
  has_many :users, through: :leases
  accepts_nested_attributes_for :property_manager




  def reviewed_leases
    self.leases.select{|l|l.review != nil}
  end

  def rating
    self.reviewed_leases.map{|l| l.rating}.inject(:+) / self.reviewed_leases.size
  end





  private

end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController

  def index
    @buildings = Building.all.select {|building| building.address.downcase.include?(params[:q].downcase)}
  end
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/buildings/index.html.erb
<h1>Building Results</h1>

<table class='table table-striped'>
  <thead class="thead-dark">
    <tr>
      <th>Address</th>
      <th>Property Manager</th>
    </tr>
  </thead>
  <% @buildings.each do |building| %>
    <tr>
      <td><%= link_to building.address, building_path(building) %></td>
      <td><%= link_to building.property_manager.name, property_manager_path(building.property_manager) %></td>
    </tr>
  <% end %>
</table>