config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :leases
  resources :buildings
  resources :property_managers do
    resources :reviews, only: [:index]
  end
  resources :users


  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  root 'application#home'
  get '/about', to: 'application#about', as: :about
  get '/statistics', to:'application#statistics',as: :statistics

  delete '/reviews/:id', to: 'reviews#destroy', as: :delete_review

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/leases_controller.rb
class LeasesController < ApplicationController


  def new
    @user = User.find(session[:user_id])
    @lease = Lease.new
  end

  def create
    @lease = Lease.new(lease_params)
    if @lease.save
      redirect_to @lease
    else
      render :new
    end
  end

  def show
    @user = User.find(session[:user_id])
    @lease = Lease.find(params[:id])
  end

  def destroy
    @user = User.find(session[:user_id])
    @lease = Lease.find(params[:id])
    @lease.destroy
    redirect_to @user
  end

  private

  def lease_params
    params.require(:lease).permit(:user_id, :building_id, :rent, :current)
  end

end

app/helpers/leases_helper.rb
module LeasesHelper
end

app/views/leases/new.html.erb
<div class="wrapper">
  <div class="sm-form-wrapper">
    <h1>Add Your lease</h1>

    <%= form_tag new_lease_path, method: 'get' do  %>
      <div class="form-group">
        <%= label_tag :address %>
        <%= text_field_tag :address, params[:address], class:"form-control" %>
      </div>
      <div class="form-group">
        <%= label_tag :borough%>
        <%= text_field_tag :borough, params[:borough], class:"form-control" %>
      </div>
      <% if !params[:address] %>
        <%= submit_tag "Submit", class:"btn btn-primary" %>
      <% end %>
    <% end %>



    <% if params[:address] || params[:name] %>
      <% @building = Building.find_or_create_by(address:params[:address], borough:params[:borough]) %>

      <% if !@building.property_manager #if building has no p manager%>

        <%= form_tag new_lease_path, method: 'get' do %>
          <br>
          <%= hidden_field_tag :address, @building.address %>
          <%= hidden_field_tag :borough, @building.borough %>
          <div class="form-group">
            <%= label_tag :name, "Property Manager Name" %>
            <%= text_field_tag :name, params[:name], class:"form-control" %>
          </div>
          <% if !params[:name] %>
            <%= submit_tag "Submit", class:"btn btn-primary"%>
          <% end %>
        <% end #end new pm form %>
      <% end #end if !@b.pm %>

      <% if params[:name] && @building %>
        <% @pm = PropertyManager.find_or_create_by(name: params[:name]) %>
        <% @building.property_manager = @pm %>
        <% @building.save %>
      <% end %>

      <br>

      <% if Building.all.include?(@building) %>
        <%= form_for @lease do |f| %>
          <%= f.hidden_field :user_id, value: @user.id %>
          <%= f.hidden_field :building_id, value: @building.id %>
          <div class="form-group">
            <%= f.label :rent %><br>
            <%= f.text_field :rent, class:"form-control" %><br>
          </div>
          <div class="form-check">
            <%= f.check_box :current, class:"form-check-input" %>
            <%= f.label :current, class:"form-check-label" %>
          </div>
          <br>
          <%= f.submit class:"btn btn-primary" %>
        <% end %>
      <% end %>




    <% end # end if params[:address]%>
  </div>
</div>

app/views/leases/show.html.erb
<div class="wrapper">

<h1>Lease</h1>

<table class="table sm-table">
  <tr>
    <th scope="row">Property Manager:</th>
    <td><h2><%= link_to @lease.building.property_manager.name, property_manager_path(@lease.building.property_manager) %></h2></td>
  </tr>
  <tr>
    <th scope="row">Address:</th>
    <td><h2><%= @lease.building.address %></h2></td>
  </tr>
  <tr>
    <th scope="row">Tenant:</th>
    <td><h2><%= @lease.user.name %></h2></td>
  </tr>
  <tr>
    <th scope="row">Monthly Rent:</th>
    <td><h2>$<%= @lease.rent %></h2></td>
  </tr>
  <tr>
    <th scope="row">Current Lease?</th>
    <td>
      <h2><%= "True" if @lease.current == true %>
      <%= "False" if @lease.current == false %></h2>
    </td>
  </tr>


</table>


</div>

<div class="wrapper wrapper-last">
  <div class="box">
    <% if @lease.review %>
      <%= link_to 'View Review', review_path(@lease.review), class:"btn btn-outline-info btn-sm" %>
    <% else %>
      <%= link_to 'Write Review', new_review_path, class:"btn btn-outline-info btn-sm" %>
    <% end %>
    <%= button_to 'Delete Lease', lease_path(@lease), method: :delete, class:"btn btn-outline-info btn-sm" %>
    <%= link_to 'Home Page', user_path(@user), method: :get, class:"btn btn-outline-info btn-sm" %>
  </div>

</div>